version: '2'
services:
  mongo-api:
    container_name: mongodb-api
    build:
      context: .
    logging:
      driver: json-file
    environment:
      PORT: $PORT
      MONGO_URI: $MONGO_URI
      LOG: 1
    volumes:
      - ./src:/app/src
    ports:
      - $PORT:$PORT
  mongo:
    container_name: mongo
    build: mongo
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: development
